import Chats from './Chats'
import ForgotPassword from './ForgotPassword'
import Friends from './Friends'
import Home from './Home'
import Layout from './Layout'
import Login from './Login'
import UserProfile from './Myprofile'
import NotFound from './NotFound'
import Notifications from './Notifications'
import Register from './Register'
import ResetPassword from './ResetPassword'
import Spotlight from './Spotlight'
import Stories from './Stories'

export { Chats, ForgotPassword, Friends, Home, Layout, Login, UserProfile, NotFound, Notifications, Register, ResetPassword, Spotlight, Stories }